"""Forecastability package implementing AMI and pAMI analysis."""

from forecastability.adapters.csv import (
    CsvGeometryBatchItem,
    CsvGeometryBatchResult,
    run_ami_geometry_csv_batch,
)
from forecastability.diagnostics.gcmi import compute_gcmi
from forecastability.metrics.scorers import (
    DependenceScorer,
    ScorerInfo,
    ScorerRegistry,
    default_registry,
    gcmi_scorer,
)
from forecastability.pipeline.analyzer import (
    AnalyzeResult,
    ForecastabilityAnalyzer,
    ForecastabilityAnalyzerExog,
)
from forecastability.reporting.fingerprint_reporting import (
    build_fingerprint_markdown,
    build_fingerprint_panel_markdown,
    build_fingerprint_summary_dict,
    build_fingerprint_summary_row,
    render_fingerprint_summary_dict,
    save_fingerprint_bundle_json,
)
from forecastability.reporting.forecastability_workbench_reporting import (
    build_batch_forecastability_executive_markdown,
    build_batch_forecastability_markdown,
)
from forecastability.triage.forecastability_profile import ForecastabilityProfile
from forecastability.triage.models import (
    TriageRequest,
    TriageResult,
)
from forecastability.triage.predictive_info_learning_curve import PredictiveInfoLearningCurve
from forecastability.triage.spectral_predictability import SpectralPredictabilityResult
from forecastability.use_cases import (
    run_batch_forecastability_workbench,
    run_batch_triage,
    run_covariant_analysis,
    run_lagged_exogenous_triage,
    run_triage,
)
from forecastability.use_cases.batch_forecastability_workbench_models import (
    BatchForecastabilityWorkbenchItem,
    BatchForecastabilityWorkbenchResult,
    BatchForecastabilityWorkbenchSummary,
    ForecastingNextStepPlan,
)
from forecastability.use_cases.run_forecastability_fingerprint import (
    run_forecastability_fingerprint,
)
from forecastability.utils.config import (
    BenchmarkDataConfig,
    CMIConfig,
    ExogenousBenchmarkConfig,
    MetricConfig,
    ModelConfig,
    OutputConfig,
    RobustnessStudyConfig,
    RollingOriginConfig,
    SensitivityConfig,
    UncertaintyConfig,
)
from forecastability.utils.datasets import (
    ar1_theoretical_ami,
    generate_ar1,
    generate_white_noise,
)
from forecastability.utils.synthetic import (
    ExpectedFamilyMetadata,
    generate_ar1_archetype,
    generate_ar1_monotonic,
    generate_contemporaneous_only_pair,
    generate_covariant_benchmark,
    generate_directional_pair,
    generate_exogenous_driven_archetype,
    generate_fingerprint_archetypes,
    generate_known_future_calendar_pair,
    generate_lagged_exog_panel,
    generate_long_memory_archetype,
    generate_low_directness_high_penalty_archetype,
    generate_mediated_directness_drop,
    generate_mediated_low_directness_archetype,
    generate_nonlinear_mixed,
    generate_nonlinear_mixed_archetype,
    generate_routing_validation_archetypes,
    generate_seasonal_archetype,
    generate_seasonal_periodic,
    generate_structural_break_archetype,
    generate_weak_seasonal_near_threshold_archetype,
    generate_white_noise_archetype,
)
from forecastability.utils.types import (
    AmiGeometryCurvePoint,
    AmiInformationGeometry,
    BackendComparisonResult,
    CanonicalExampleResult,
    CanonicalSummary,
    CausalGraphResult,
    CovariantAnalysisBundle,
    CovariantSummaryRow,
    Diagnostics,
    ExogenousBenchmarkResult,
    FingerprintBundle,
    ForecastabilityFingerprint,
    ForecastResult,
    GcmiResult,
    InterpretationResult,
    LaggedExogBundle,
    LaggedExogProfileRow,
    LaggedExogSelectionRow,
    LagRoleLabel,
    LagSelectorLabel,
    LagSignificanceSource,
    MetricCurve,
    PcmciAmiResult,
    Phase0MiScore,
    RobustnessStudyResult,
    RoutingPolicyAudit,
    RoutingPolicyAuditConfig,
    RoutingRecommendation,
    RoutingValidationBundle,
    RoutingValidationCase,
    RoutingValidationOutcome,
    RoutingValidationSourceKind,
    SampleSizeStressResult,
    SeriesEvaluationResult,
    TensorRoleLabel,
    TransferEntropyResult,
)
from forecastability.utils.validation import validate_time_series

__version__ = "0.3.1"

__all__ = [
    "AmiGeometryCurvePoint",
    "AmiInformationGeometry",
    "AnalyzeResult",
    "ar1_theoretical_ami",
    "BackendComparisonResult",
    "BatchForecastabilityWorkbenchItem",
    "BatchForecastabilityWorkbenchResult",
    "BatchForecastabilityWorkbenchSummary",
    "CanonicalExampleResult",
    "CanonicalSummary",
    "CausalGraphResult",
    "CMIConfig",
    "CovariantAnalysisBundle",
    "CovariantSummaryRow",
    "Diagnostics",
    "build_batch_forecastability_executive_markdown",
    "build_batch_forecastability_markdown",
    "build_fingerprint_markdown",
    "build_fingerprint_panel_markdown",
    "build_fingerprint_summary_dict",
    "build_fingerprint_summary_row",
    "CsvGeometryBatchItem",
    "CsvGeometryBatchResult",
    "DependenceScorer",
    "ExpectedFamilyMetadata",
    "ExogenousBenchmarkConfig",
    "ExogenousBenchmarkResult",
    "FingerprintBundle",
    "ForecastabilityAnalyzer",
    "ForecastabilityAnalyzerExog",
    "ForecastabilityFingerprint",
    "ForecastingNextStepPlan",
    "ForecastabilityProfile",
    "ForecastResult",
    "GcmiResult",
    "gcmi_scorer",
    "compute_gcmi",
    "generate_ar1",
    "generate_ar1_archetype",
    "generate_ar1_monotonic",
    "generate_contemporaneous_only_pair",
    "generate_covariant_benchmark",
    "generate_directional_pair",
    "generate_exogenous_driven_archetype",
    "generate_fingerprint_archetypes",
    "generate_known_future_calendar_pair",
    "generate_lagged_exog_panel",
    "generate_long_memory_archetype",
    "generate_low_directness_high_penalty_archetype",
    "generate_mediated_directness_drop",
    "generate_mediated_low_directness_archetype",
    "generate_nonlinear_mixed",
    "generate_nonlinear_mixed_archetype",
    "generate_routing_validation_archetypes",
    "generate_seasonal_archetype",
    "generate_seasonal_periodic",
    "generate_structural_break_archetype",
    "generate_weak_seasonal_near_threshold_archetype",
    "generate_white_noise",
    "generate_white_noise_archetype",
    "BenchmarkDataConfig",
    "InterpretationResult",
    "LaggedExogBundle",
    "LaggedExogProfileRow",
    "LaggedExogSelectionRow",
    "LagRoleLabel",
    "LagSelectorLabel",
    "LagSignificanceSource",
    "MetricConfig",
    "MetricCurve",
    "ModelConfig",
    "OutputConfig",
    "PcmciAmiResult",
    "Phase0MiScore",
    "PredictiveInfoLearningCurve",
    "RobustnessStudyConfig",
    "RobustnessStudyResult",
    "RollingOriginConfig",
    "RoutingPolicyAudit",
    "RoutingPolicyAuditConfig",
    "RoutingRecommendation",
    "RoutingValidationBundle",
    "RoutingValidationCase",
    "RoutingValidationOutcome",
    "RoutingValidationSourceKind",
    "run_batch_triage",
    "run_batch_forecastability_workbench",
    "run_covariant_analysis",
    "run_lagged_exogenous_triage",
    "run_forecastability_fingerprint",
    "run_ami_geometry_csv_batch",
    "run_triage",
    "render_fingerprint_summary_dict",
    "SampleSizeStressResult",
    "ScorerInfo",
    "ScorerRegistry",
    "SensitivityConfig",
    "SeriesEvaluationResult",
    "SpectralPredictabilityResult",
    "TensorRoleLabel",
    "TransferEntropyResult",
    "TriageRequest",
    "TriageResult",
    "UncertaintyConfig",
    "default_registry",
    "save_fingerprint_bundle_json",
    "validate_time_series",
]
