"""Generate the forecast prep showcase artifacts for plan v0.3.4.

Outputs:
- outputs/reports/forecast_prep/contract_univariate.json
- outputs/reports/forecast_prep/contract_univariate.md
- outputs/reports/forecast_prep/lag_table_univariate.csv
- outputs/reports/forecast_prep/report.md (human summary, links to recipes)

Usage:
    uv run python scripts/run_showcase_forecast_prep.py
    uv run python scripts/run_showcase_forecast_prep.py --smoke

The script imports only from `forecastability` and `forecastability.triage`.
It does not import any forecasting framework. The end of the script prints a
pointer to docs/recipes/forecast_prep_to_external_frameworks.md so the user
knows where to take the contract next.
"""

from __future__ import annotations

import argparse
import csv
import logging
import time
from pathlib import Path

import pandas as pd

from forecastability import (
    TriageRequest,
    build_forecast_prep_contract,
    forecast_prep_contract_to_lag_table,
    forecast_prep_contract_to_markdown,
    generate_ar1,
    generate_lagged_exog_panel,
    run_lagged_exogenous_triage,
    run_triage,
)
from forecastability.triage import AnalysisGoal

_logger = logging.getLogger(__name__)

_KNOWN_FUTURE_DRIVER = "known_future_calendar"
_DRIVER_ORDER: tuple[str, ...] = (
    "direct_lag2",
    "mediated_lag1",
    "redundant",
    "noise",
    "instant_only",
    "nonlinear_lag1",
    _KNOWN_FUTURE_DRIVER,
)
_RECIPES_PATH = "docs/recipes/forecast_prep_to_external_frameworks.md"


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Forecast prep contract showcase (v0.3.4 Phase 3)")
    parser.add_argument("--output-root", type=str, default="outputs", help="output root directory")
    parser.add_argument("--random-state", type=int, default=42, help="reproducibility seed")
    parser.add_argument("--max-lag", type=int, default=24, help="maximum lag horizon")
    parser.add_argument(
        "--n-surrogates",
        type=int,
        default=99,
        help="number of surrogates; must be at least 99",
    )
    parser.add_argument(
        "--n",
        type=int,
        default=1500,
        help="number of observations",
    )
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="CI-friendly preset (n=240, max_lag=min(max_lag, 8), n_surrogates=99)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress stage banners; only print final line",
    )
    return parser.parse_args(argv)


def _resolved_n(args: argparse.Namespace) -> int:
    return 240 if args.smoke else int(args.n)


def _resolved_max_lag(args: argparse.Namespace) -> int:
    if args.smoke:
        return min(int(args.max_lag), 8)
    return int(args.max_lag)


def _ensure_dirs(output_root: Path) -> Path:
    reports_dir = output_root / "reports" / "forecast_prep"
    reports_dir.mkdir(parents=True, exist_ok=True)
    return reports_dir


def _say(quiet: bool, message: str) -> None:
    if not quiet:
        print(message, flush=True)


def _write_lag_table_csv(path: Path, contract: object) -> None:
    from forecastability import ForecastPrepContract

    assert isinstance(contract, ForecastPrepContract)
    rows = forecast_prep_contract_to_lag_table(contract)
    if rows:
        fieldnames = list(rows[0].keys())
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
    else:
        path.write_text("", encoding="utf-8")


def _build_report_markdown(
    *,
    contract_version: str,
    confidence_label: str,
    recommended_target_lags: list[int],
    recommended_families: list[str],
    calendar_features: list[str],
    smoke: bool,
    elapsed_univariate: float,
) -> str:
    mode_label = "smoke" if smoke else "full"
    lines = [
        "# Forecast Prep Showcase Report",
        "",
        f"Generated by `scripts/run_showcase_forecast_prep.py` (mode: {mode_label}).",
        "",
        "## Univariate Contract Summary",
        "",
        f"- **contract_version**: {contract_version}",
        f"- **confidence_label**: {confidence_label}",
        f"- **recommended_target_lags**: {recommended_target_lags}",
        f"- **recommended_families**: {recommended_families}",
        f"- **calendar_features** ({len(calendar_features)} total): "
        + (", ".join(calendar_features[:5]) + (" …" if len(calendar_features) > 5 else "")),
        f"- **elapsed (univariate triage + contract build)**: {elapsed_univariate:.2f}s",
        "",
        "## What to do next",
        "",
        "The `ForecastPrepContract` is a hand-off artifact. Carry it to a downstream",
        "forecasting framework using the recipes page:",
        "",
        f"    See: {_RECIPES_PATH}",
        "",
        "The recipes page maps each contract field to framework-specific constructor",
        "arguments for darts, mlforecast, statsforecast, and nixtla — but those",
        "framework imports live there, not here.",
        "",
        "## Artifacts",
        "",
        "- `contract_univariate.json` — full contract serialised as JSON",
        "- `contract_univariate.md`  — human-readable markdown summary",
        "- `lag_table_univariate.csv` — flat lag table for inspection",
        "- `report.md`               — this file",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run the forecast-prep showcase and return POSIX-style exit code."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(name)s  %(message)s")

    args = _parse_args(argv)
    if args.n_surrogates < 99:
        raise ValueError(f"n_surrogates must be >= 99, got {args.n_surrogates}")

    n_obs = _resolved_n(args)
    max_lag = _resolved_max_lag(args)
    quiet = bool(args.quiet)
    random_state = int(args.random_state)
    n_surrogates = int(args.n_surrogates)

    output_root = Path(args.output_root)
    reports_dir = _ensure_dirs(output_root)

    _say(quiet, "=" * 72)
    _say(quiet, "[forecast-prep-showcase] v0.3.4-Phase3 canonical run")
    _say(quiet, "=" * 72)
    _say(quiet, f"[forecast-prep-showcase] mode           : {'smoke' if args.smoke else 'full'}")
    _say(quiet, f"[forecast-prep-showcase] n              : {n_obs}")
    _say(quiet, f"[forecast-prep-showcase] max_lag        : {max_lag}")
    _say(quiet, f"[forecast-prep-showcase] n_surrogates   : {n_surrogates}")
    _say(quiet, f"[forecast-prep-showcase] random_state   : {random_state}")
    _say(quiet, f"[forecast-prep-showcase] output_root    : {output_root}")
    _say(quiet, "")

    # -------------------------------------------------------------------------
    # Step 1: Univariate triage + calendar-aware ForecastPrepContract
    # -------------------------------------------------------------------------
    t_uni = time.perf_counter()

    series = generate_ar1(n_samples=n_obs, phi=0.8, random_state=random_state)
    dates = pd.date_range(start="2020-01-01", periods=n_obs, freq="D")

    triage_result = run_triage(
        TriageRequest(
            series=series,
            goal=AnalysisGoal.univariate,
            max_lag=max_lag,
            n_surrogates=n_surrogates,
            random_state=random_state,
        )
    )

    contract_uni = build_forecast_prep_contract(
        triage_result,
        horizon=12,
        target_frequency="D",
        add_calendar_features=True,
        datetime_index=dates,
        calendar_locale=None,
    )

    elapsed_uni = time.perf_counter() - t_uni
    _say(
        quiet,
        f"[forecast-prep-showcase] step 1/3  univariate triage + contract built "
        f"[{elapsed_uni:.2f}s]",
    )

    # -------------------------------------------------------------------------
    # Step 2 (full mode only): Covariate-aware contract with lagged exog panel
    # -------------------------------------------------------------------------
    if not args.smoke:
        t_cov = time.perf_counter()
        panel = generate_lagged_exog_panel(n=n_obs, seed=random_state)
        cov_target = panel["target"].to_numpy()
        drivers = {driver: panel[driver].to_numpy() for driver in _DRIVER_ORDER}

        lagged_exog_bundle = run_lagged_exogenous_triage(
            cov_target,
            drivers,
            target_name="target",
            max_lag=min(max_lag, 12),
            n_surrogates=n_surrogates,
            random_state=random_state,
            known_future_drivers={_KNOWN_FUTURE_DRIVER: True},
        )

        cov_triage = run_triage(
            TriageRequest(
                series=cov_target,
                goal=AnalysisGoal.univariate,
                max_lag=max_lag,
                n_surrogates=n_surrogates,
                random_state=random_state,
            )
        )

        _contract_cov = build_forecast_prep_contract(
            cov_triage,
            horizon=12,
            target_frequency="D",
            lagged_exog_bundle=lagged_exog_bundle,
            known_future_drivers={_KNOWN_FUTURE_DRIVER: True},
            add_calendar_features=False,
        )

        _say(
            quiet,
            f"[forecast-prep-showcase] step 2/3  covariate-aware contract built "
            f"[{time.perf_counter() - t_cov:.2f}s]",
        )
    else:
        _say(quiet, "[forecast-prep-showcase] step 2/3  skipped in smoke mode")

    # -------------------------------------------------------------------------
    # Step 3: Write outputs
    # -------------------------------------------------------------------------
    t_write = time.perf_counter()

    json_path = reports_dir / "contract_univariate.json"
    md_path = reports_dir / "contract_univariate.md"
    csv_path = reports_dir / "lag_table_univariate.csv"
    report_path = reports_dir / "report.md"

    json_path.write_text(contract_uni.model_dump_json(indent=2), encoding="utf-8")
    md_path.write_text(forecast_prep_contract_to_markdown(contract_uni), encoding="utf-8")
    _write_lag_table_csv(csv_path, contract_uni)
    report_path.write_text(
        _build_report_markdown(
            contract_version=str(contract_uni.contract_version),
            confidence_label=str(contract_uni.confidence_label),
            recommended_target_lags=list(contract_uni.recommended_target_lags),
            recommended_families=list(contract_uni.recommended_families),
            calendar_features=list(contract_uni.calendar_features),
            smoke=bool(args.smoke),
            elapsed_univariate=elapsed_uni,
        ),
        encoding="utf-8",
    )

    elapsed_write = time.perf_counter() - t_write
    _say(
        quiet,
        f"[forecast-prep-showcase] step 3/3  wrote artifacts [{elapsed_write:.2f}s]",
    )
    _say(quiet, f"[forecast-prep-showcase]           -> {json_path}")
    _say(quiet, f"[forecast-prep-showcase]           -> {md_path}")
    _say(quiet, f"[forecast-prep-showcase]           -> {csv_path}")
    _say(quiet, f"[forecast-prep-showcase]           -> {report_path}")
    _say(quiet, "")

    print(
        f"See {_RECIPES_PATH} for framework-specific adapters (darts, mlforecast, statsforecast).",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
