# Migration shim — canonical location is forecastability.domain.value_objects.types
# Remove this shim in v0.6.0
from __future__ import annotations

import warnings as _warnings

from forecastability.domain.value_objects.types import (  # noqa: F401
    AmiGeometryCurvePoint,
    AmiInformationGeometry,
    BackendComparisonEntry,
    BackendComparisonResult,
    CanonicalExampleResult,
    CanonicalSummary,
    CausalGraphResult,
    CovariantAnalysisBundle,
    CovariantDriverRole,
    CovariantInterpretationResult,
    CovariantMethodConditioning,
    CovariantRoleTag,
    CovariantSummaryRow,
    CovariateRecommendation,
    Diagnostics,
    ExogenousBenchmarkResult,
    ExogenousDriverSummary,
    ExogenousHorizonUsefulnessRow,
    ExogenousLagWindowSummaryRow,
    ExogenousScreeningWorkbenchResult,
    FamilyRecommendation,
    FingerprintBundle,
    FingerprintStructure,
    ForecastabilityFingerprint,
    ForecastPrepBundle,
    ForecastPrepConfidence,
    ForecastPrepContract,
    ForecastPrepContractConfidence,
    ForecastPrepCovariateRole,
    ForecastPrepFamilyTier,
    ForecastPrepLagRole,
    ForecastPrepTargetHistoryContext,
    ForecastResult,
    GcmiResult,
    GeometryMethodLabel,
    InterpretationResult,
    LaggedExogBundle,
    LaggedExogConditioningTag,
    LaggedExogProfileRow,
    LaggedExogSelectionRow,
    LagRecommendation,
    LagRoleLabel,
    LagSelectorLabel,
    LagSignificanceSource,
    MetricCurve,
    ModelFamilyLabel,
    PcmciAmiResult,
    Phase0MiScore,
    RobustnessStudyResult,
    RoutingCautionFlag,
    RoutingConfidenceLabel,
    RoutingPolicyAudit,
    RoutingPolicyAuditConfig,
    RoutingRecommendation,
    RoutingValidationBundle,
    RoutingValidationCase,
    RoutingValidationOutcome,
    RoutingValidationSourceKind,
    SampleSizeStressEntry,
    SampleSizeStressResult,
    SeriesEvaluationResult,
    TensorRoleLabel,
    TransferEntropyResult,
)

_warnings.warn(
    "forecastability.utils.types is deprecated in v0.5.0; "
    "use forecastability.domain.value_objects.types instead. "
    "See docs/migration/v0.4.x_to_v0.5.0.md.",
    DeprecationWarning,
    stacklevel=2,
)
